[package]
name = "idt8a3xxx"
version = "0.1.0"
authors = ["Bryan Cantrill <bryan@oxide.computer>"]
edition = "2018"

[build-dependencies]
ron = "0.6"
serde = "1.0.126"
anyhow = "1.0.31"

[dependencies]
